# Generated by Django 2.2.3 on 2019-07-15 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('type', models.CharField(choices=[('APT', 'Apartment'), ('DPL', 'Duplex')], max_length=25, verbose_name='Type of Property')),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('area', models.IntegerField(verbose_name='Total Area in Sq')),
                ('room_number', models.IntegerField(verbose_name='Total Number of Rooms')),
                ('availability', models.DateField(verbose_name='Available From')),
                ('slug', models.SlugField(blank=True, max_length=20, unique=True)),
                ('shared', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='property', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('BTH', 'Bathroom'), ('BDR', 'Bedroom')], max_length=40)),
                ('room_size', models.IntegerField(verbose_name='Room Size in Sq')),
                ('total', models.IntegerField(verbose_name='Number of this Room')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='main.Property')),
            ],
            options={
                'ordering': ['room_size'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease', models.CharField(choices=[('6MON', '6 Months'), ('12MON', '12 Months')], max_length=25, verbose_name='Lease Type')),
                ('price', models.IntegerField(verbose_name='Lease Price')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='main.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='upload')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.Property')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
