# Generated by Django 2.2.2 on 2019-06-30 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=2000)),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('type', models.CharField(choices=[('APT', 'Apartment'), ('DPL', 'Duplex')], max_length=25)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('area', models.IntegerField()),
                ('room_number', models.IntegerField()),
                ('lease_type', models.CharField(choices=[('6MON', '6 Months'), ('12MON', '12 Months')], max_length=25)),
                ('availability', models.DateField()),
                ('slug', models.SlugField(blank=True, max_length=20, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('BTH', 'Bathroom'), ('BDR', 'Bedroom')], max_length=40)),
                ('room_size', models.IntegerField()),
                ('total', models.IntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='main.Property')),
            ],
            options={
                'ordering': ['room_size'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='upload')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.Property')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
