# Generated by Django 2.2.2 on 2019-06-30 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='lease_type',
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.IntegerField(verbose_name='Total Area in Sq'),
        ),
        migrations.AlterField(
            model_name='property',
            name='availability',
            field=models.DateField(verbose_name='Available From'),
        ),
        migrations.AlterField(
            model_name='property',
            name='room_number',
            field=models.IntegerField(verbose_name='Total Number of Rooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('APT', 'Apartment'), ('DPL', 'Duplex')], max_length=25, verbose_name='Type of Property'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_size',
            field=models.IntegerField(verbose_name='Room Size in Sq'),
        ),
        migrations.AlterField(
            model_name='room',
            name='total',
            field=models.IntegerField(verbose_name='Number of this Room'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease', models.CharField(choices=[('6MON', '6 Months'), ('12MON', '12 Months')], max_length=25, verbose_name='Lease Type')),
                ('price', models.IntegerField(verbose_name='Lease Price')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Property')),
            ],
        ),
    ]
